#ifndef ROBOT_MOUTH_H
#define ROBOT_MOUTH_H

#include "Arduino.h"

#define MOUTH_START_COLUMN    0x30
#define MOUTH_END_COLUMN      0x4F
#define MOUTH_START_PAGE      0x05
#define MOUTH_END_PAGE        0x06

#define MOUTH_COLUMNS         ((MOUTH_END_COLUMN - MOUTH_START_COLUMN) + 1)
#define MOUTH_PAGES           ((MOUTH_END_PAGE - MOUTH_START_PAGE) + 1)
#define MOUTH_BYTES           (MOUTH_COLUMNS * MOUTH_PAGES)

typedef enum{
    
  ROBOTMOUTH_HAPPY,
  ROBOTMOUTH_SAD,
  ROBOTMOUTH_CONFUSE,
  ROBOTMOUTH_SHOCK,
  ROBOTMOUTH_NONE,
  ROBOTMOUTH_MAX
  
}ROBOT_MOUTH;

extern byte mouths[ROBOTMOUTH_MAX-1][MOUTH_BYTES];


#endif
